version: '3.8'

services:
  rentacar_db :
    image: postgres:15-alpine
    container_name: rentacar-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - punarent_data:/var/lib/postgresql/data

volumes:
  rentacar_data: